### ISSUE TITLE
Filter out duplicate torrents

### ISSUE THREAD

**Issue by thomasasfk** [thomasasfk/PlexSearchBotSimple#5]
Sometimes when searching for anime there are duplicate torrents:

`/search kimetsu no yaiba`

![image](https://github.com/thomasasfk/PlexSearchBotSimple/assets/22506439/fbeccd76-afb2-4cc1-92e0-95da340cdcd4)

There is probably some unique identifier we can filter them by, so we stop showing duplicates unnecessarily.

**Comment by selmdev** [comment]
Just use the ID from the URL silly

**Comment by thomasasfk** [comment]
> Just use the ID from the URL retard


Dear Selm,

Thank you for your participation and input.

I would kindly request that you refrain from using insulting or derogatory language on our issue board. We strive to foster an atmosphere of friendly and constructive discourse, where all participants feel respected and valued.

Regarding the matter at hand, I would like to address your suggestion of using the ID from the URL. It is important to note that the ID in the URL is not necessarily unique for each result. The underlying issue appears to be within Jackett, as it is generating duplicate results with distinct URLs.

In my opinion, it would be more appropriate to utilize the Guid value. This identifier is unique for each torrent and not dependent on the specific Jackett result.

Thank you for your understanding and cooperation.

Best regards,
Thomas

**Comment by thomasasfk** [comment]
https://github.com/thomasasfk/PlexSearchBotSimple/pull/7
