### ISSUE TITLE
If message is too long, truncate results

### ISSUE THREAD

**Issue by thomasasfk** [thomasasfk/PlexSearchBotSimple#6]
Sometimes, if the 25 results returned have long names and the message surpasses the threshold, sending the message will fail.  

The user isn't notified of this, so it just looks like the bot isn't working, cause no error message either.

We should dynamically add the results based on the threshold, and ensure we don't go over it.

**Comment by 12932** [comment]
Whats the Telegram max character limit?

**Comment by thomasasfk** [comment]
> Whats the Telegram max character limit?

4096 characters

**Comment by thomasasfk** [comment]
Maybe we should just make the result limit like 15 or 20:

https://github.com/thomasasfk/PlexSearchBotSimple/blob/5d98158e618bf8f950c42d044dff75c431c8c89a/feral_services/jackett.py#L45-L50

Since any no body scrolling that high anyways.

**Comment by 12932** [comment]
True but then that still doesn't guarantee its under the character limit, we need a function thats smarter

**Comment by thomasasfk** [comment]
> True but then that still doesn't guarantee its under the character limit, we need a function thats smarter

Okay we can do that later but I've done https://github.com/thomasasfk/PlexSearchBotSimple/pull/7 for now
